# Generated by Django 3.2.13 on 2022-10-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_running_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recommended',
            field=models.IntegerField(default=0),
        ),
    ]
