# Generated by Django 3.2.13 on 2022-10-18 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
